//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverestVideoLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVDDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVDDetail()
        {
            this.CastMembers = new HashSet<CastMember>();
            this.DVDCopies = new HashSet<DVDCopy>();
            this.ProducerDVDDetailsMappings = new HashSet<ProducerDVDDetailsMapping>();
        }
    
        public int DVDId { get; set; }
        public string Title { get; set; }
        public int DVDCatId { get; set; }
        public int StudioId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CastMember> CastMembers { get; set; }
        public virtual DVDCategory DVDCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDCopy> DVDCopies { get; set; }
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducerDVDDetailsMapping> ProducerDVDDetailsMappings { get; set; }
    }
}
