//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverestVideoLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberCategory()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int MemberCatId { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public int TotalDays { get; set; }
        public int TotalLoan { get; set; }
        public int FineAmountPerDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
