//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverestVideoLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerDVDDetailsMapping
    {
        public int proDVDmapping { get; set; }
        public int DVDId { get; set; }
        public int ProducerId { get; set; }
    
        public virtual DVDDetail DVDDetail { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
